### ISSUE TITLE
Evaluation Error on require of puppet/util/rundeck_acl

### ISSUE THREAD

**Issue by johnzimm** [voxpupuli/puppet-rundeck#125]
Referencing: eaf068ac8a0d0502ea9a075821583800d30439df

https://github.com/puppet-community/puppet-rundeck/blob/eaf068ac8a0d0502ea9a075821583800d30439df/lib/puppet/parser/functions/validate_rd_policy.rb#L1

Running Puppet OSS 4.2 with module cloned from the commit referenced above.

Full error message from the puppet agent run is...

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppet/util/rundeck_acl at /etc/puppetlabs/code/environments/rundeck/modules/rundeck/manifests/init.pp:169:3 on node mynodename.local
```

**Comment by dandunckelman** [comment]
I get a similar error on Puppet v3.8.2.

    Error:  Could not retrieve catalog from remote server: Error 400 on SERVER; Could not autoload puppet/parser/functions/validate_rd_policy: cannot load such file -- puppet/util/rundeck_acl on node rundeck-dev.local

I'm unsure if this is something that can be resolved by this module.  For now, I'm pinned to ref:  587c9192bd67468d7cd28aff2b3be51281e409cf

**Comment by liamjbennett** [comment]
I think there are a couple of issues that might be causing this and I do belive it is a problem with the module.

I think it missing a `module_functions` declaration.

Also clearly it is missing tests to catch this problem in the first place.

**Comment by dandunckelman** [comment]
@liamjbennett oh, that makes sense.  Thanks!

**Comment by johnzimm** [comment]
Anyone else experiencing this issue?  Just saw a new version was tagged (v2.0.0).

**Comment by liamjbennett** [comment]
I have been trying to replicate this in the beaker tests but have not been able to yet. 

v2.0.0 was indeed released recently as there were many other changes people were asking for.

**Comment by liamjbennett** [comment]
The two things I think the related to:
1) the util file needs to be moved to the puppetx namespace 
2) we need to do a relative require on the file for the poor people still on ruby 1.8.7

**Comment by igalic** [comment]
ad 1) puppetx -> puppetcommunityx

**Comment by Tombar** [comment]
same for me on puppet 3.8.3 with plugingsync=true on both puppetmaster and node

any pointer on how to fix it? tried messing with the module structure without luck

thanks

M

**Comment by ak0ska** [comment]
We have the issue as well, Puppet 3.7.5, Ruby 2.0.0, CentOS7 on masters and agents.

@Tombar 
I shamefully admit I did the following less-than-pretty change locally to get it working.
```diff
--- a/code/lib/puppet/parser/functions/validate_rd_policy.rb
+++ b/code/lib/puppet/parser/functions/validate_rd_policy.rb
@@ -1,4 +1,5 @@
-require 'puppet/util/rundeck_acl'
+#require 'puppet/util/rundeck_acl'
+File.expand_path('../../util/rundeck_acl', __FILE__)
``` 
In my defence [official modules](https://github.com/puppetlabs/puppetlabs-inifile/blob/master/lib/puppet/provider/ini_setting/ruby.rb) also do things like that. ;)

**Comment by JesperTerkelsen** [comment]
I also have this problem on my puppet server.

**Comment by Tombar** [comment]
I've tested @ak0ska suggestion from @JesperTerkelsen fork and it work as expected.

Please merge this change :)

Regards

M

**Comment by johnzimm** [comment]
@JesperTerkelsen can you submit a pull request for your changes?

**Comment by Tombar** [comment]
Just submit PR #140 with @ak0ska and @JesperTerkelsen suggestions to speed up things.

Regards

M

**Comment by rooty0** [comment]
hey @liamjbennett, 
so I was able to reproduce this issue with ruby
```
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Puppet 3.8.3
```

I was unable to reproduce the issue on my virtual machine with the same version of ruby (Puppet 3.7.4).

Wondering if it's really related to ruby's version

**Comment by JesperTerkelsen** [comment]
@johnzimm I made the pr.

**Comment by liamjbennett** [comment]
Fixed with #146

**Comment by jyaworski** [comment]
@liamjbennett I don't believe this is fixed. I pulled down the newest git, cleared all of my caches, and tried running it. Same error.

**Comment by liamjbennett** [comment]
What version of puppet are you running? I tested it myself with 3.8.3 and ruby 1.9.3p484

**Comment by jyaworski** [comment]
@liamjbennett failed with both 4.2 and 4.3.

**Comment by f3rr** [comment]
Same problem here
- puppet 3.8.2
- ruby 2.0.0

**Comment by icalvete** [comment]
Still broken

- puppet 3.8.1
- commit 96903339b010f5622535532298a47b59b1e07e33
- ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by SydOps** [comment]
@liamjbennett 

Can we re-open this ticket, it is still broken.

**Comment by SydOps** [comment]
And the way @ak0ska commented on Oct 7, 2015 works. But please fix it in master branch directly.

**Comment by KrisBuytaert** [comment]
+1 same issue here ;(

**Comment by mkrakowitzer** [comment]
+1 same issue
puppet 4.3.2

**Comment by richardraseley** [comment]
+1 I am also still seeing this as of today with version 2.2.0.

Puppet 4.2.3

**Comment by richardraseley** [comment]
This is fixed for me in a commit <= ac505369b1fd77568858af166d673287cfb84a4a .

👍

**Comment by igalic** [comment]
is this issue resolved now after merging #201?

**Comment by KrisBuytaert** [comment]
@igalic  looks like it solved it in my vagrant box ..

**Comment by igalic** [comment]
thanks for the feedback @KrisBuytaert!

**Comment by kilianw** [comment]
FYI, Not as successful on: 
CentOS 6.8
ruby 1.8.7
puppet v3.7.5
